/**
 * Tests for the tpdc_execute MCP tool wrapper.
 *
 * Mocks runExecute (which has its own real-git integration tests). We focus
 * on input validation, argument plumbing, and response shape — the things
 * the MCP wrapper is responsible for.
 */

import { beforeEach, describe, expect, it, vi } from "vitest";

import type { PlanArtifact } from "../../stages/plan/plan.schema.js";

vi.mock("../../stages/execute/execute.js", () => ({
  runExecute: vi.fn(),
}));

import { runExecute } from "../../stages/execute/execute.js";
import { executeTool } from "./execute.js";

function parseResult(text: string): unknown {
  return JSON.parse(text);
}

const validPlan: PlanArtifact = {
  title: "Add password reset flow",
  objective: "Self-service password reset.",
  steps: [
    {
      stepNumber: 1,
      title: "Add reset request endpoint",
      description: "Email-triggered token generation.",
      acceptanceCriteria: ["POST /reset returns 200"],
      dependencies: [],
      expectedFiles: ["src/auth/reset.ts"],
    },
  ],
  riskLevel: "medium",
  validationApproach: "Run `npm test`.",
  testCommands: ["npm test"],
  assumptions: [],
  blockers: [],
  readiness: "ready",
};

const validArgs = {
  runId: "run-001",
  intakeTitle: "Add password reset",
  plan: validPlan,
  repoRoot: "/tmp/fake-repo",
};

function makeExecuteResult(
  overrides: Partial<Parameters<typeof runExecute>[0]> = {},
): Awaited<ReturnType<typeof runExecute>> {
  return {
    runId: "run-001",
    status: "completed",
    worktreePath: "/tmp/fake-repo/.tpdc/worktrees/run-001",
    branch: "tpdc/run-run-001",
    baseSha: "abcdef1234567890",
    commitSha: "fedcba0987654321",
    commitMessage: "Add password reset\n\nGenerated by TPDC v2 (run run-001)",
    filesChanged: ["src/auth/reset.ts"],
    diff: "+ console.log('ok');",
    finalSummary: "Implemented reset endpoint.",
    toolCallCount: 5,
    turnCount: 4,
    usage: { inputTokens: 1000, outputTokens: 500 },
    model: "claude-sonnet-4-6",
    // biome-ignore lint/suspicious/noExplicitAny: overrides escape hatch
    ...(overrides as any),
  };
}

describe("executeTool — metadata", () => {
  it("has the expected name + required input shape", () => {
    expect(executeTool.name).toBe("tpdc_execute");
    expect(executeTool.inputSchema.required).toEqual([
      "runId",
      "intakeTitle",
      "plan",
      "repoRoot",
    ]);
  });
});

describe("executeTool — happy path", () => {
  beforeEach(() => {
    vi.mocked(runExecute).mockReset();
  });

  it("calls runExecute with the canonical request and returns the result JSON", async () => {
    vi.mocked(runExecute).mockResolvedValueOnce(makeExecuteResult());

    const result = await executeTool.handler(validArgs);

    expect(result.isError).toBeUndefined();
    expect(vi.mocked(runExecute)).toHaveBeenCalledOnce();
    const passed = vi.mocked(runExecute).mock.calls[0]?.[0];
    expect(passed?.runId).toBe("run-001");
    expect(passed?.plan).toEqual(validPlan);
    expect(passed?.repoRoot).toBe("/tmp/fake-repo");

    const block = result.content[0];
    if (block?.type !== "text") throw new Error("expected text block");
    const parsed = parseResult(block.text) as {
      runId: string;
      status: string;
      filesChanged: string[];
    };
    expect(parsed.runId).toBe("run-001");
    expect(parsed.status).toBe("completed");
    expect(parsed.filesChanged).toEqual(["src/auth/reset.ts"]);
  });

  it("forwards optional maxTurns to runExecute", async () => {
    vi.mocked(runExecute).mockResolvedValueOnce(makeExecuteResult());
    await executeTool.handler({ ...validArgs, maxTurns: 30 });
    expect(vi.mocked(runExecute).mock.calls[0]?.[0]?.maxTurns).toBe(30);
  });

  it("omits maxTurns from the runExecute call when not given (lets default apply)", async () => {
    vi.mocked(runExecute).mockResolvedValueOnce(makeExecuteResult());
    await executeTool.handler(validArgs);
    expect(vi.mocked(runExecute).mock.calls[0]?.[0]?.maxTurns).toBeUndefined();
  });

  it("forwards existingWorktree (fix-mode reuse)", async () => {
    vi.mocked(runExecute).mockResolvedValueOnce(makeExecuteResult());
    const wt = {
      path: "/tmp/fake-repo/.tpdc/worktrees/run-001",
      branch: "tpdc/run-run-001",
      baseSha: "abcdef1234567890",
    };
    await executeTool.handler({ ...validArgs, existingWorktree: wt });
    expect(vi.mocked(runExecute).mock.calls[0]?.[0]?.existingWorktree).toEqual(wt);
  });

  it("forwards failureContext for fix-mode", async () => {
    vi.mocked(runExecute).mockResolvedValueOnce(makeExecuteResult());
    const fc = {
      attempt: 2,
      previousCommands: [
        { command: "npm test", exitCode: 1, stdout: "", stderr: "boom" },
      ],
      previousFinalSummary: "First attempt failed.",
    };
    await executeTool.handler({ ...validArgs, failureContext: fc });
    expect(vi.mocked(runExecute).mock.calls[0]?.[0]?.failureContext).toEqual(fc);
  });

  it("reports max_turns_exceeded without flagging isError (the run did not throw)", async () => {
    vi.mocked(runExecute).mockResolvedValueOnce(
      makeExecuteResult({ status: "max_turns_exceeded" } as any),
    );
    const result = await executeTool.handler(validArgs);
    expect(result.isError).toBeUndefined();
    const block = result.content[0];
    if (block?.type !== "text") throw new Error("expected text block");
    const parsed = parseResult(block.text) as { status: string };
    expect(parsed.status).toBe("max_turns_exceeded");
  });
});

describe("executeTool — validation", () => {
  beforeEach(() => vi.mocked(runExecute).mockReset());

  it("returns isError:true when required field is missing", async () => {
    const result = await executeTool.handler({
      ...validArgs,
      // biome-ignore lint/suspicious/noExplicitAny: deliberate
      runId: undefined as any,
    });
    expect(result.isError).toBe(true);
    expect(vi.mocked(runExecute)).not.toHaveBeenCalled();
    const block = result.content[0];
    if (block?.type !== "text") throw new Error("expected text block");
    const parsed = parseResult(block.text) as { ok: boolean; errors: Array<{ path: string }> };
    expect(parsed.ok).toBe(false);
    expect(parsed.errors.some((e) => e.path === "runId")).toBe(true);
  });

  it("returns isError:true when plan is malformed", async () => {
    const result = await executeTool.handler({
      ...validArgs,
      // biome-ignore lint/suspicious/noExplicitAny: deliberate
      plan: { ...validPlan, riskLevel: "yolo" } as any,
    });
    expect(result.isError).toBe(true);
    expect(vi.mocked(runExecute)).not.toHaveBeenCalled();
    const block = result.content[0];
    if (block?.type !== "text") throw new Error("expected text block");
    const parsed = parseResult(block.text) as { errors: Array<{ path: string }> };
    expect(parsed.errors.some((e) => e.path === "plan.riskLevel")).toBe(true);
  });

  it("returns isError:true when maxTurns is out of range", async () => {
    const result = await executeTool.handler({ ...validArgs, maxTurns: 500 });
    expect(result.isError).toBe(true);
    expect(vi.mocked(runExecute)).not.toHaveBeenCalled();
  });
});

describe("executeTool — runtime errors", () => {
  beforeEach(() => vi.mocked(runExecute).mockReset());

  it("returns isError:true when runExecute throws", async () => {
    vi.mocked(runExecute).mockRejectedValueOnce(
      new Error("repoRoot is not a git repository"),
    );

    const result = await executeTool.handler(validArgs);
    expect(result.isError).toBe(true);
    const block = result.content[0];
    if (block?.type !== "text") throw new Error("expected text block");
    const parsed = parseResult(block.text) as {
      ok: boolean;
      error: string;
      stage: string;
      runId: string;
    };
    expect(parsed.ok).toBe(false);
    expect(parsed.error).toMatch(/not a git repository/);
    expect(parsed.stage).toBe("execute");
    expect(parsed.runId).toBe("run-001");
  });
});
