/**
 * Execute Patch Mode — repo-aware patch generation.
 *
 * Wraps runCapability("execute-patch") with repo context injection.
 * Does NOT apply patches. Output is a PatchArtifact.
 *
 * Supports chunked mode: when the plan has multiple steps, generates
 * patches per-step with scoped repo context, then merges results.
 * This prevents LLM timeouts on large plans.
 */

import * as crypto from "crypto";
import { runCapability, RunResult, RunMetadata } from "./runCapability";
import { LLMAdapter } from "./types";
import { buildRepoContext } from "./repoContext";
import { saveArtifact } from "../storage/local";

export interface ExecutePatchOptions {
  llm: LLMAdapter;
  repoRoot: string;
  fileHints?: string[];
  runId?: string;
  quiet?: boolean;
  /** Force single-shot mode even with multiple steps */
  chunked?: boolean;
}

interface PlanStep {
  stepNumber: number;
  title: string;
  description: string;
  acceptanceCriteria: string;
  goal?: string;
  surface?: string;
  executionContext?: string;
  stackAssumption?: string;
  dependencies?: number[];
}

interface PatchEntry {
  stepNumber: number;
  filePath: string;
  operation: "create" | "modify" | "delete";
  diff: string;
  justification: string;
}

/** Threshold: plans with more steps than this use chunked mode by default */
const CHUNK_THRESHOLD = 2;

export async function executePatch(
  planArtifact: Record<string, unknown>,
  options: ExecutePatchOptions,
): Promise<RunResult> {
  const steps = (planArtifact.steps as PlanStep[]) || [];
  const planStatus = planArtifact.status as string | undefined;

  // Blocked plans go straight through (no chunking needed)
  if (planStatus === "blocked" || steps.length === 0) {
    return executeSingleShot(planArtifact, options);
  }

  // Determine chunking mode
  const useChunked = options.chunked !== undefined
    ? options.chunked
    : steps.length > CHUNK_THRESHOLD;

  if (!useChunked) {
    return executeSingleShot(planArtifact, options);
  }

  return executeChunked(planArtifact, steps, options);
}

/**
 * Original single-shot mode: send entire plan + all repo context in one call.
 */
async function executeSingleShot(
  planArtifact: Record<string, unknown>,
  options: ExecutePatchOptions,
): Promise<RunResult> {
  const { llm, repoRoot, fileHints = [], runId, quiet } = options;

  const steps = (planArtifact.steps as PlanStep[]) || [];
  const repoCtx = buildRepoContext(repoRoot, steps, fileHints);

  const augmentedInput = {
    plan: planArtifact,
    repoContext: {
      repoRoot: repoCtx.repoRoot,
      existingFiles: repoCtx.existingFiles,
      fileContents: repoCtx.fileContents,
    },
  };

  return runCapability("execute-patch", augmentedInput, {
    llm,
    runId,
    quiet,
  });
}

/**
 * Chunked mode: generate patches per-step with scoped context, then merge.
 */
async function executeChunked(
  planArtifact: Record<string, unknown>,
  steps: PlanStep[],
  options: ExecutePatchOptions,
): Promise<RunResult> {
  const { llm, repoRoot, fileHints = [], runId, quiet } = options;
  const log = quiet ? (() => {}) : console.log.bind(console);
  const effectiveRunId = runId ?? `run_${Date.now()}_${crypto.randomBytes(4).toString("hex")}`;
  const startTime = Date.now();

  log(`[ExecutePatch] Chunked mode: ${steps.length} steps`);

  const allPatches: PatchEntry[] = [];
  const allAssumptions: string[] = [];
  const allRisks: string[] = [];
  const allNotes: string[] = [];
  const targetFilesSet = new Set<string>();
  const stepResults: Array<{ stepNumber: number; status: string; patchCount: number; error?: string }> = [];
  let hasPartial = false;

  // Collect file contents generated by previous steps (for create operations)
  const createdFiles: Record<string, string> = {};

  for (const step of steps) {
    log(`[ExecutePatch]   Step ${step.stepNumber}: ${step.title}`);

    // Build repo context scoped to this step's files only
    const stepRepoCtx = buildRepoContext(repoRoot, [step], fileHints);

    // Merge in file contents from previously created files
    // so subsequent steps can reference files created earlier
    for (const [filePath, content] of Object.entries(createdFiles)) {
      if (!stepRepoCtx.fileContents[filePath]) {
        stepRepoCtx.existingFiles.push(filePath);
        stepRepoCtx.fileContents[filePath] = content;
      }
    }

    // Build a mini-plan with just this step but full plan context
    const miniPlan = {
      sourceTicket: planArtifact.sourceTicket,
      designTitle: planArtifact.designTitle,
      status: "actionable",
      changeStrategy: planArtifact.changeStrategy,
      steps: [step],
      risks: planArtifact.risks,
      validationPlan: planArtifact.validationPlan,
    };

    const augmentedInput = {
      plan: miniPlan,
      repoContext: {
        repoRoot: stepRepoCtx.repoRoot,
        existingFiles: stepRepoCtx.existingFiles,
        fileContents: stepRepoCtx.fileContents,
      },
    };

    try {
      const result = await runCapability("execute-patch", augmentedInput, {
        llm,
        runId: `${effectiveRunId}_step${step.stepNumber}`,
        quiet: true,
      });

      const output = result.output as Record<string, unknown>;
      const status = output.executionStatus as string;

      if (status === "blocked" || status === "insufficient_context") {
        hasPartial = true;
        stepResults.push({ stepNumber: step.stepNumber, status, patchCount: 0 });
        log(`[ExecutePatch]   Step ${step.stepNumber}: ${status}`);
        continue;
      }

      const patches = (output.patches as PatchEntry[]) || [];
      stepResults.push({ stepNumber: step.stepNumber, status, patchCount: patches.length });

      // Track created files for subsequent steps
      for (const patch of patches) {
        if (patch.operation === "create" && patch.diff) {
          // Extract new file content from diff (lines starting with +, excluding +++ header)
          const lines = patch.diff.split("\n");
          const contentLines = lines
            .filter(l => l.startsWith("+") && !l.startsWith("+++"))
            .map(l => l.substring(1));
          createdFiles[patch.filePath] = contentLines.join("\n");
        }
      }

      allPatches.push(...patches);
      for (const p of patches) targetFilesSet.add(p.filePath);

      const assumptions = (output.assumptions as string[]) || [];
      const risks = (output.risks as string[]) || [];
      const notes = output.notes as string;

      allAssumptions.push(...assumptions);
      allRisks.push(...risks);
      if (notes) allNotes.push(`Step ${step.stepNumber}: ${notes}`);

      if (status === "partial") hasPartial = true;

      log(`[ExecutePatch]   Step ${step.stepNumber}: ${patches.length} patch(es)`);

    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      hasPartial = true;
      stepResults.push({ stepNumber: step.stepNumber, status: "error", patchCount: 0, error: message.split("\n")[0] });
      log(`[ExecutePatch]   Step ${step.stepNumber}: ERROR — ${message.split("\n")[0]}`);
    }
  }

  const durationMs = Date.now() - startTime;

  // Build merged PatchArtifact
  const executionStatus = allPatches.length === 0
    ? "blocked"
    : hasPartial ? "partial" : "completed";

  const mergedOutput: Record<string, unknown> = {
    sourceTicket: planArtifact.sourceTicket ?? "",
    planTitle: planArtifact.designTitle ?? "",
    executionMode: "patch",
    executionStatus,
    targetFiles: [...targetFilesSet],
    changeSummary: `Chunked execution: ${allPatches.length} patch(es) across ${steps.length} steps. ${stepResults.filter(s => s.status === "completed" || s.status === "partial").length}/${steps.length} steps produced patches.`,
    patches: allPatches,
    assumptions: [...new Set(allAssumptions)],
    risks: [...new Set(allRisks)],
    notes: allNotes.length > 0 ? allNotes.join("\n") : "Generated via chunked patch mode.",
  };

  if (executionStatus === "blocked" && allPatches.length === 0) {
    mergedOutput.blockedReason = `All ${steps.length} steps failed to produce patches. Step results: ${stepResults.map(s => `step ${s.stepNumber}: ${s.status}`).join(", ")}`;
  }

  // Persist merged artifact
  const savedTo = saveArtifact(effectiveRunId, "execute-patch", mergedOutput);
  saveArtifact(effectiveRunId, "execute-patch.chunk-log", stepResults);

  // Build metadata
  const metadata: RunMetadata = {
    runId: effectiveRunId,
    capabilityId: "execute-patch",
    capabilityVersion: "0.1.0",
    adapterId: llm.adapterInfo.adapterId,
    modelId: llm.adapterInfo.modelId,
    transport: llm.adapterInfo.transport,
    timestamp: new Date().toISOString(),
    validated: true,
    validationErrors: [],
    durationMs,
  };

  saveArtifact(effectiveRunId, "metadata", metadata);

  log(`[ExecutePatch] Chunked complete: ${allPatches.length} patches, ${executionStatus} (${(durationMs / 1000).toFixed(1)}s)`);

  return {
    runId: effectiveRunId,
    capabilityId: "execute-patch",
    version: "0.1.0",
    output: mergedOutput,
    validated: true,
    savedTo,
    metadata,
  };
}
