/**
 * PR body template — TPDC v2.
 *
 * Renders a markdown PR body from the artifacts of intake/plan/execute/run-tests.
 * Pure helper — no I/O, no side effects, no external API calls. Easy to unit-test.
 *
 * The body is structured for a human reviewer to evaluate:
 *   - Summary: what this PR does (intake's title + problem statement)
 *   - Acceptance Criteria: binary checks the change must satisfy
 *   - Plan: ordered steps with their AC
 *   - Validation: commands run + results
 *   - Files Changed: list from execute
 *   - Footer: TPDC run id + how to inspect
 */

import type { IntakeArtifact } from "../intake/intake.schema.js";
import type { PlanArtifact } from "../plan/plan.schema.js";
import type { ExecuteResult } from "../execute/execute.schema.js";
import type { RunTestsResult } from "../run-tests/run-tests.schema.js";

export interface BodyContext {
  runId: string;
  intake: IntakeArtifact;
  plan: PlanArtifact;
  execute: ExecuteResult;
  tests: RunTestsResult;
}

const TPDC_FOOTER_MARKER = "<!-- generated-by-tpdc-v2 -->";

export function renderPRBody(ctx: BodyContext): string {
  const sections: string[] = [];

  sections.push(renderSummary(ctx));
  sections.push(renderAcceptanceCriteria(ctx));
  sections.push(renderPlan(ctx));
  sections.push(renderValidation(ctx));
  sections.push(renderFilesChanged(ctx));
  sections.push(renderFooter(ctx));

  return sections.filter((s) => s.length > 0).join("\n\n");
}

export function renderPRTitle(ctx: BodyContext): string {
  // Use the intake title; if too long, truncate. GitHub PR titles allow up to 256
  // chars but conventional commit-style PR titles fit ~72.
  const title = ctx.intake.title.trim();
  return title.length > 100 ? `${title.slice(0, 97)}...` : title;
}

function renderSummary(ctx: BodyContext): string {
  return [
    "## Summary",
    "",
    ctx.intake.problemStatement,
  ].join("\n");
}

function renderAcceptanceCriteria(ctx: BodyContext): string {
  if (ctx.intake.acceptanceCriteria.length === 0) return "";
  const lines = ["## Acceptance Criteria", ""];
  for (const ac of ctx.intake.acceptanceCriteria) {
    lines.push(`- [x] ${ac}`);
  }
  return lines.join("\n");
}

function renderPlan(ctx: BodyContext): string {
  const lines = [
    "## Plan",
    "",
    ctx.plan.objective,
    "",
    `**Risk:** ${ctx.plan.riskLevel}`,
    "",
    "### Steps",
    "",
  ];

  for (const step of ctx.plan.steps) {
    lines.push(`${step.stepNumber}. **${step.title}**`);
    lines.push(`   ${step.description}`);
    if (step.dependencies.length > 0) {
      lines.push(`   _Depends on: ${step.dependencies.map((d) => `#${d}`).join(", ")}_`);
    }
    lines.push("");
  }

  if (ctx.plan.assumptions.length > 0) {
    lines.push("### Assumptions");
    lines.push("");
    for (const a of ctx.plan.assumptions) {
      lines.push(`- ${a}`);
    }
  }

  return lines.join("\n").trimEnd();
}

function renderValidation(ctx: BodyContext): string {
  const lines = [
    "## Validation",
    "",
    ctx.plan.validationApproach,
    "",
  ];

  if (ctx.tests.results.length === 0) {
    lines.push("_No automated validation commands were run._");
    return lines.join("\n").trimEnd();
  }

  lines.push("### Test Results");
  lines.push("");
  for (const r of ctx.tests.results) {
    const icon = r.status === "passed" ? "✅" : r.status === "failed" ? "❌" : "⚠️";
    const tail = r.status === "passed"
      ? ""
      : r.status === "failed"
        ? ` (exit ${r.exitCode})`
        : ` (${r.errorMessage ?? r.signal ?? "errored"})`;
    lines.push(`- ${icon} \`${r.command}\`${tail} — ${r.durationMs}ms`);
  }
  lines.push("");
  lines.push(
    `**Summary:** ${ctx.tests.summary.passed}/${ctx.tests.summary.total} commands passed (${ctx.tests.totalDurationMs}ms total)`,
  );

  return lines.join("\n");
}

function renderFilesChanged(ctx: BodyContext): string {
  if (ctx.execute.filesChanged.length === 0) {
    return ["## Files Changed", "", "_No files changed._"].join("\n");
  }
  const lines = ["## Files Changed", ""];
  for (const f of ctx.execute.filesChanged) {
    lines.push(`- \`${f}\``);
  }
  return lines.join("\n");
}

function renderFooter(ctx: BodyContext): string {
  return [
    "---",
    "",
    `<sub>Generated by TPDC v2 · run \`${ctx.runId}\` · branch \`${ctx.execute.branch}\` · ${ctx.execute.turnCount} turn(s) / ${ctx.execute.toolCallCount} tool call(s) · ${ctx.execute.usage.inputTokens}+${ctx.execute.usage.outputTokens} tokens</sub>`,
    "",
    TPDC_FOOTER_MARKER,
  ].join("\n");
}

/** Exposed for tests / detection of TPDC-generated PR bodies. */
export const TPDC_BODY_MARKER = TPDC_FOOTER_MARKER;
